name: Build and deploy app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10.16.3

      - name: Update npm
        run:  npm install -g npm@5

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ./SimpleApplication/node_modules
          key: dependency-cache-${{ hashFiles('SimpleApplication/package-lock.json') }}
          restore-key: |
            dependency-cache-

      - name: Install dependencies
        run: npm install

      - name: Build docker image
        run: docker build -t simple-app:latest .

      - name: Save image
        uses: actions/upload-artifact@v3
        with:
          name: simple-app-docker-image
          path: /tmp/simple-app.tar

      - name: Export image
        run: docker save -o /tmp/simple-app.tar simple-app:latest